export const pozeLucrari = [
    { src: "/poze/a2/a2_01.jpg", text: "Autostrada A2, măsurători marcaje, 20km lungime" },
    { src: "/poze/blocuri/blocuri_01.jpg", text: "Bloc Mamaia Nord, trasare contur stâlpi." },
    { src: "/poze/blocuri/blocuri_02.jpg", text: "Bloc Mamaia Nord, trasare ziduri exterioare." },
    { src: "/poze/blocuri/blocuri_03.jpg", text: "Bloc Mamaia Nord, trasare ziduri exterioare." },
    { src: "/poze/blocuri/blocuri_04.jpg", text: "Bloc Mamaia Nord, transmitere punct pe tavan pentru o verticalitate perfectă." },
    { src: "/poze/blocuri/blocuri_05.jpg", text: "Bloc Mamaia Nord, verificare ax suport ghidaj pentru fațade." },
    { src: "/poze/blocuri/blocuri_06.jpg", text: "Bloc Mamaia Nord, trasare cu prismă de înaltă precizie." },
    { src: "/poze/blocuri/blocuri_07.jpg", text: "Bloc Mamaia Nord, 3 luni de trasări zilnice la zidărie, ferestre, balustrade." },
    { src: "/poze/blocuri/blocuri_08.jpg", text: "Bloc Mamaia Nord." },
    { src: "/poze/blocuri/blocuri_09.jpg", text: "Bloc Mamaia Nord, trasare pereți interiori." },
    { src: "/poze/blocuri/blocuri_10.jpg", text: "Precizia la trasări este esențială." },
    { src: "/poze/blocuri/blocuri_11.jpg", text: "Bloc Mamaia Nord, trasare zidărie." },
    { src: "/poze/blocuri/blocuri_12.jpg", text: "Bloc Mamaia Nord, pregătire pentru trasare balustrade sticlă." },
    { src: "/poze/blocuri/blocuri_13.jpg", text: "Bloc Mamaia Nord, vedere generală la final de proiect." },
    { src: "/poze/cernavoda/cern_01.jpg", text: "Parc Cernavodă, trasare borduri." },
    { src: "/poze/cernavoda/cern_02.jpg", text: "Parc Cernavodă, trasare borduri." },
    { src: "/poze/cf/cfpn01.jpg", text: "Piatra Neamț, măsurători cale ferată." },
    { src: "/poze/cf/cfpn02.jpg", text: "Piatra Neamț, măsurători cale ferată." },
    { src: "/poze/cf/cfpn03.jpg", text: "Piatra Neamț, măsurători cale ferată." },
    { src: "/poze/cf/cfpn04.jpg", text: "Piatra Neamț, măsurători cale ferată." },
    { src: "/poze/cf/cfpn05.jpg", text: "Piatra Neamț, măsurători cale ferată." },
    { src: "/poze/cf/cfport01.jpg", text: "Port Constanța, trasare cale ferată nouă." },
    { src: "/poze/cf/cfport02.jpg", text: "Port Constanța, măsurători cale ferată veche." },
    { src: "/poze/cf/cfport03.jpg", text: "Port Constanța, măsurători cale ferată veche." },
    { src: "/poze/cf/cfport04.jpg", text: "Port Constanța, trasare cale ferată nouă." },
    { src: "/poze/cumpana/cump_01.jpg", text: "Cumpăna, alunecare teren, măsurători frecvente pentru a stabili viteza de deplasare." },
    { src: "/poze/cumpana/cump_02.jpg", text: "Cumpăna, alunecare teren, măsurători frecvente pentru a stabili viteza de deplasare." },
    { src: "/poze/cumpana/cump_03.jpg", text: "Cumpăna, alunecare teren, măsurători frecvente pentru a stabili viteza de deplasare." },
    { src: "/poze/cumpana/cump_04.jpg", text: "Cumpăna, alunecare teren, măsurători frecvente pentru a stabili viteza de deplasare." },
    { src: "/poze/dig/dig_01.jpg", text: "Dig Mamaia, trasări." },
    { src: "/poze/dig/dig_02.jpg", text: "Dig Mamaia, trasări." },
    { src: "/poze/dig/dig_03.jpg", text: "Dig Mamaia, trasări." },
    { src: "/poze/dig/dig_04.jpg", text: "Dig Mamaia, trasări." },
    { src: "/poze/dig/dig_05.jpg", text: "Dig Mamaia, trasări." },
    { src: "/poze/dig/dig_06.jpg", text: "Dig Mamaia, trasări." },
    { src: "/poze/dig/dig_07.jpg", text: "Dig Mamaia, finalizat." },
    { src: "/poze/diverse/caraimanMamaia01.jpg", text: "Hotel Caraiman, măsurători pentru cadastru." },
    { src: "/poze/diverse/caraimanMamaia02.jpg", text: "Hotel Caraiman, măsurători pentru cadastru." },
    { src: "/poze/diverse/div01.jpg", text: "Măsurători diverse." },
    { src: "/poze/diverse/div02.jpg", text: "Măsurători diverse." },
    { src: "/poze/diverse/div03.jpg", text: "Măsurători diverse." },
    { src: "/poze/diverse/drumJudet.jpg", text: "Măsurători drumuri." },
    { src: "/poze/diverse/elmont.jpg", text: "Măsurători stâlpi electricitate." },
    { src: "/poze/diverse/iaki.jpg", text: "Iaki Mamaia, măsurători 3D pentru reabilitare fațade sticlă." },
    { src: "/poze/diverse/lafargeMedgidia.jpg", text: "Lafarge Medgidia, măsurători 3D." },
    { src: "/poze/diverse/metro01.jpg", text: "Metro 1 Constanța, trasări și măsurători." },
    { src: "/poze/diverse/metro02.jpg", text: "Metro 1 Constanța, trasări și măsurători." },
    { src: "/poze/diverse/metro03.jpg", text: "Metro 1 Constanța, trasări și măsurători." },
    { src: "/poze/diverse/metro04.jpg", text: "Metro 1 Constanța, trasări și măsurători." },
    { src: "/poze/diverse/metro05.jpg", text: "Metro 1 Constanța, trasări și măsurători." },
    { src: "/poze/diverse/portConstanta.jpg", text: "Port Constanța, trasări cale ferată." },
    { src: "/poze/diverse/releveuHotelEforie.jpg", text: "Hotel Eforie Nord, relevee." },
    { src: "/poze/diverse/tuzlaDrum.jpg", text: "Tuzla Aeroport, verificat cote proiect la drum." },
    { src: "/poze/diverse/tuzlaPista01.jpg", text: "Tuzla Aeroport, trasat margine pistă." },
    { src: "/poze/trasari/tuzla_01.jpg", text: "Tuzla Aeroport, trasare marcaje." },
    { src: "/poze/trasari/tuzla_02.jpg", text: "Tuzla Aeroport, trasare marcaje." },
    { src: "/poze/eoliene/eo_01.jpg", text: "CEZ România, verificări senzori direcție vânt." },
    { src: "/poze/eoliene/eo_02.jpg", text: "CEZ România, verificări senzori direcție vânt." },
    { src: "/poze/eoliene/eo_03.jpg", text: "CEZ România, verificări senzori direcție vânt." },
    // { src: "/poze/eoliene/eo_04.jpg", text: "CEZ România, verificări senzori direcție vânt." },
    { src: "/poze/ovidiu/ovidiu_01.jpg", text: "Parc Ovidiu, trasare platfome beton." },
    { src: "/poze/ovidiu/ovidiu_02.jpg", text: "Parc Ovidiu, trasare aspersoare." },
    { src: "/poze/trasari/trs02.jpg", text: "Metro 1 Constanța, trasare limite săpătură." },
    { src: "/poze/trasari/trs03.jpg", text: "Metro 1 Constanța, trasare limite ziduri." },
    { src: "/poze/trasari/trs04.jpg", text: "Metro 1 Constanța, trasare marcaje rutiere." },
    { src: "/poze/trasari/trs05.jpg", text: "Metro 1 Constanța, trasare marcaje rutiere." },
    { src: "/poze/trasari/trs06.jpg", text: "Metro 1 Constanța, trasare marcaje rutiere." },
    { src: "/poze/trasari/trs07.jpg", text: "Metro 1 Constanța, verificat cote proiect zid de sprijin." },
    { src: "/poze/trasari/trs08.jpg", text: "Metro 1 Constanța, trasări diverse." },
    { src: "/poze/trasari/trs09.jpg", text: "Hală Constanța zona industriala, trasare axe stâlpi." },
    { src: "/poze/trasari/trs10.jpg", text: "Hală Constanța zona industriala, trasare axe stâlpi." },
    { src: "/poze/trasari/trs11.jpg", text: "Bloc Constanța, verificat axe si cote proiect." },
    { src: "/poze/turn/turn_01.jpg", text: "Constanța, măsurat înalțime stâlp metalic." },
]